version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:9040"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
